ypkg: dependency indicator fixed.

diff --git a/ypkg b/ypkg
--- a/ypkg
+++ b/ypkg
@@ -1,5 +1,5 @@
 #!/bin/sh
-## $Id: ypkg,v 1.3 2013/03/23 04:38:45 yozo Exp $
+## $Id: ypkg,v 1.4 2013/03/23 05:54:26 yozo Exp $
 ##
 
 PKGDBPATH=/var/db/pkg
@@ -34,7 +34,7 @@ expand_tabs(){
 ##   done
 ## }
 
-show_dependents(){ ## arg1: recursion depth,  arg2: pkgname
+show_dependents(){ ## arg1: recursion depth,  arg2: pkgname,  arg3: parent pkgname (when arg1 > 0)
     pkgname=`cd ${PKGDBPATH} && ls | grep $2`
     pkgnamematched=`echo ${pkgname} | wc -w`
     if [ $pkgnamematched -ge 2 ]; then
@@ -44,7 +44,11 @@ show_dependents(){ ## arg1: recursion depth,  arg2: pkgname
     fi
     expand_tabs "$1"
     if [ -f "${PKGDBPATH}/${pkgname}/+REQUIRED_BY" ]; then
-      echo -n "*"
+      if [ "$1" -eq 0 ]; then
+        echo -n "*"
+      elif [ -n "`grep -v "$3" "${PKGDBPATH}/${pkgname}/+REQUIRED_BY"`" ]; then
+        echo -n "*"
+      fi
     fi
     echo "[$1] ${pkgname}"
     requiring="${PKGDBPATH}/${pkgname}/+REQUIRING"
@@ -52,11 +56,36 @@ show_dependents(){ ## arg1: recursion depth,  arg2: pkgname
       depends=`cat ${requiring}`
       depth=`expr 1 + $1`
       for i in ${depends}; do
-        ## show_dependents "${depth}" "$i"
-        show_dependents `expr 1 + $1` "$i"
+        show_dependents `expr 1 + $1` "$i" "${pkgname}"
       done
     fi
 }
+
+## show_dependents_child(){ ## arg1: recursion depth,  arg2: pkgname,  arg3: parent pkgname
+##     pkgname=`cd ${PKGDBPATH} && ls | grep $2`
+##     pkgnamematched=`echo ${pkgname} | wc -w`
+##     if [ $pkgnamematched -ge 2 ]; then
+##         echo "ERROR! ambiguous package name"
+##         echo "$pkgname"
+##         exit 20
+##     fi
+##     expand_tabs "$1"
+##     if [ -f "${PKGDBPATH}/${pkgname}/+REQUIRED_BY" ]; then
+##       if [ -n "`grep -v "$3" "${PKGDBPATH}/${pkgname}/+REQUIRED_BY"`" ]; then
+##         echo -n "*"
+##       fi
+##     fi
+##     echo "[$1] ${pkgname}"
+##     requiring="${PKGDBPATH}/${pkgname}/+REQUIRING"
+##     if [ -f ${requiring} ]; then
+##       depends=`cat ${requiring}`
+##       depth=`expr 1 + $1`
+##       for i in ${depends}; do
+##         ## show_dependents "${depth}" "$i"
+##         show_dependents_child `expr 1 + $1` "$i" "${pkgname}"
+##       done
+##     fi
+## }
 
 
 ## main routine starts here
